### ISSUE TITLE
AEGNN_DATA_DIR Issue

### ISSUE THREAD

**Issue by csoubhik-kgpian** [uzh-rpg/aegnn#22]
I keep getting this issue:

Traceback (most recent call last):
  File "aegnn/scripts/train.py", line 77, in <module>
    main(arguments)
  File "aegnn/scripts/train.py", line 43, in main
    dm.setup()
  File "/home/20mi91w02/.conda/envs/aegnn/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 428, in wrapped_fn
    fn(*args, **kwargs)
  File "/scratch/20mi91w02/aegnn/aegnn/datasets/base/event_dm.py", line 43, in setup
    raise UserWarning("No data found, check AEGNN_DATA_DIR environment variable!")
UserWarning: No data found, check AEGNN_DATA_DIR environment variable!

Though I have set the env variable 
>>> print(os.environ['AEGNN_DATA_DIR'])
/scratch/20mi91w02/aegnn/data/storage

Please help

**Comment by Lxy-2018** [comment]
Hello, I have also encountered the exact same problem. Did you successfully run it? If so, what is the AEGNN_DATA_DIR you filled in and the path where the dataset is located? I hope to receive any help. Thanks.
``
